version: '3.1'
services:
  api:
    build: ./api
    expose:
      - 8000
    volumes:
      - data:/data
    command: --bind 0.0.0.0:8000 app:app
  web:
    build: ./web
    ports:
      - 8080:80
    depends_on:
      - api
  wallet:
    image: ingimarsson/smileycoin:latest
    expose:
      - 14242
    volumes:
      - data:/data

volumes:
  data:
